# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:36:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerTournamentProjectionID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    SlateTournamentID: Optional[int] = None


class Injury(BaseModel):
    Active: Optional[bool] = None
    BodyPart: Optional[str] = None
    ExpectedReturn: Optional[str] = None
    InjuryID: Optional[int] = None
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    StartDate: Optional[str] = None
    Status: Optional[str] = None


class News(BaseModel):
    Author: Optional[str] = None
    Categories: Optional[str] = None
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    OriginalSource: Optional[str] = None
    OriginalSourceUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Source: Optional[str] = None
    TermsOfUse: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthDate: Optional[str] = None
    BirthState: Optional[str] = None
    College: Optional[str] = None
    Country: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    PgaDebut: Optional[int] = None
    PgaTourPlayerID: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    SportRadarPlayerID: Optional[str] = None
    Swings: Optional[str] = None
    Weight: Optional[int] = None
    YahooPlayerID: Optional[int] = None


class PlayerHole(BaseModel):
    Birdie: Optional[bool] = None
    Bogey: Optional[bool] = None
    DoubleBogey: Optional[bool] = None
    DoubleEagle: Optional[bool] = None
    Eagle: Optional[bool] = None
    HoleInOne: Optional[bool] = None
    IsPar: Optional[bool] = None
    Number: Optional[int] = None
    Par: Optional[int] = None
    PlayerRoundID: Optional[int] = None
    Score: Optional[int] = None
    ToPar: Optional[int] = None
    WorseThanDoubleBogey: Optional[bool] = None


class PlayerRound(BaseModel):
    BackNineStart: Optional[bool] = None
    Birdies: Optional[int] = None
    BogeyFree: Optional[bool] = None
    Bogeys: Optional[int] = None
    BounceBackCount: Optional[float] = None
    ConsecutiveBirdieOrBetterCount: Optional[float] = None
    Day: Optional[str] = None
    DoubleBogeys: Optional[int] = None
    DoubleEagles: Optional[int] = None
    Eagles: Optional[int] = None
    HoleInOnes: Optional[int] = None
    Holes: Optional[List[PlayerHole]] = None
    IncludesFiveOrMoreBirdiesOrBetter: Optional[bool] = None
    IncludesStreakOfFiveBirdiesOrBetter: Optional[bool] = None
    IncludesStreakOfFourBirdiesOrBetter: Optional[bool] = None
    IncludesStreakOfSixBirdiesOrBetter: Optional[bool] = None
    IncludesStreakOfThreeBirdiesOrBetter: Optional[bool] = None
    LongestBirdieOrBetterStreak: Optional[float] = None
    Number: Optional[int] = None
    Par: Optional[int] = None
    Pars: Optional[int] = None
    PlayerRoundID: Optional[int] = None
    PlayerTournamentID: Optional[int] = None
    Score: Optional[int] = None
    TeeTime: Optional[str] = None
    TripleBogeys: Optional[int] = None
    WorseThanDoubleBogey: Optional[int] = None
    WorseThanTripleBogey: Optional[int] = None


class PlayerSeason(BaseModel):
    AveragePoints: Optional[float] = None
    Events: Optional[int] = None
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerSeasonID: Optional[int] = None
    PointsGained: Optional[float] = None
    PointsLost: Optional[float] = None
    Season: Optional[int] = None
    TotalPoints: Optional[float] = None
    WorldGolfRank: Optional[int] = None
    WorldGolfRankLastWeek: Optional[int] = None


class PlayerTournament(BaseModel):
    Birdies: Optional[float] = None
    BogeyFreeRounds: Optional[float] = None
    Bogeys: Optional[float] = None
    BounceBackCount: Optional[float] = None
    ConsecutiveBirdieOrBetterCount: Optional[float] = None
    Country: Optional[str] = None
    DoubleBogeys: Optional[float] = None
    DoubleEagles: Optional[float] = None
    DraftKingsSalary: Optional[int] = None
    Eagles: Optional[float] = None
    Earnings: Optional[float] = None
    FanDuelSalary: Optional[int] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FedExPoints: Optional[int] = None
    HoleInOnes: Optional[float] = None
    IsAlternate: Optional[bool] = None
    IsWithdrawn: Optional[bool] = None
    MadeCut: Optional[float] = None
    MadeCutDidNotFinish: Optional[bool] = None
    Name: Optional[str] = None
    OddsToWin: Optional[float] = None
    OddsToWinDescription: Optional[str] = None
    Pars: Optional[float] = None
    PlayerID: Optional[int] = None
    PlayerTournamentID: Optional[int] = None
    Rank: Optional[int] = None
    Rounds: Optional[List[PlayerRound]] = None
    RoundsUnderSeventy: Optional[float] = None
    RoundsWithFiveOrMoreBirdiesOrBetter: Optional[float] = None
    StreaksOfFiveBirdiesOrBetter: Optional[float] = None
    StreaksOfFourBirdiesOrBetter: Optional[float] = None
    StreaksOfSixBirdiesOrBetter: Optional[float] = None
    StreaksOfThreeBirdiesOrBetter: Optional[float] = None
    TeeTime: Optional[str] = None
    TotalScore: Optional[float] = None
    TotalStrokes: Optional[float] = None
    TotalThrough: Optional[int] = None
    TournamentID: Optional[int] = None
    TournamentStatus: Optional[str] = None
    TripleBogeys: Optional[float] = None
    Win: Optional[float] = None
    WorseThanDoubleBogey: Optional[float] = None
    WorseThanTripleBogey: Optional[float] = None


class PlayerTournamentProjection(BaseModel):
    Birdies: Optional[float] = None
    BogeyFreeRounds: Optional[float] = None
    Bogeys: Optional[float] = None
    BounceBackCount: Optional[float] = None
    ConsecutiveBirdieOrBetterCount: Optional[float] = None
    Country: Optional[str] = None
    DoubleBogeys: Optional[float] = None
    DoubleEagles: Optional[float] = None
    DraftKingsSalary: Optional[int] = None
    Eagles: Optional[float] = None
    Earnings: Optional[float] = None
    FanDuelSalary: Optional[int] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FedExPoints: Optional[int] = None
    HoleInOnes: Optional[float] = None
    IsAlternate: Optional[bool] = None
    IsWithdrawn: Optional[bool] = None
    MadeCut: Optional[float] = None
    MadeCutDidNotFinish: Optional[bool] = None
    Name: Optional[str] = None
    OddsToWin: Optional[float] = None
    OddsToWinDescription: Optional[str] = None
    Pars: Optional[float] = None
    PlayerID: Optional[int] = None
    PlayerTournamentID: Optional[int] = None
    Rank: Optional[int] = None
    Rounds: Optional[List[PlayerRound]] = None
    RoundsUnderSeventy: Optional[float] = None
    RoundsWithFiveOrMoreBirdiesOrBetter: Optional[float] = None
    StreaksOfFiveBirdiesOrBetter: Optional[float] = None
    StreaksOfFourBirdiesOrBetter: Optional[float] = None
    StreaksOfSixBirdiesOrBetter: Optional[float] = None
    StreaksOfThreeBirdiesOrBetter: Optional[float] = None
    TeeTime: Optional[str] = None
    TotalScore: Optional[float] = None
    TotalStrokes: Optional[float] = None
    TotalThrough: Optional[int] = None
    TournamentID: Optional[int] = None
    TournamentStatus: Optional[str] = None
    TripleBogeys: Optional[float] = None
    Win: Optional[float] = None
    WorseThanDoubleBogey: Optional[float] = None
    WorseThanTripleBogey: Optional[float] = None


class Round(BaseModel):
    Day: Optional[str] = None
    Number: Optional[int] = None
    RoundID: Optional[int] = None
    TournamentID: Optional[int] = None


class Season(BaseModel):
    Description: Optional[str] = None
    EndDate: Optional[str] = None
    SeasonID: Optional[int] = None
    StartDate: Optional[str] = None


class Tournament(BaseModel):
    Canceled: Optional[bool] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    Covered: Optional[bool] = None
    EndDate: Optional[str] = None
    Format: Optional[str] = None
    IsInProgress: Optional[bool] = None
    IsOver: Optional[bool] = None
    Location: Optional[str] = None
    Name: Optional[str] = None
    Par: Optional[int] = None
    Purse: Optional[float] = None
    Rounds: Optional[List[Round]] = None
    SportRadarTournamentID: Optional[str] = None
    StartDate: Optional[str] = None
    StartDateTime: Optional[str] = None
    State: Optional[str] = None
    TimeZone: Optional[str] = None
    TournamentID: Optional[int] = None
    Venue: Optional[str] = None
    Yards: Optional[int] = None
    ZipCode: Optional[str] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatInjuriesGetResponse(RootModel[List[Injury]]):
    root: List[Injury]


class FieldFormatInjuriesByHistoricalGetResponse(RootModel[List[Injury]]):
    root: List[Injury]


class FieldFormatNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByPlayerIDPlayeridGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatPlayerSeasonStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerTournamentProjectionStatsTournamentidGetResponse(
    RootModel[List[PlayerTournamentProjection]]
):
    root: List[PlayerTournamentProjection]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatTournamentsGetResponse(RootModel[List[Tournament]]):
    root: List[Tournament]


class FieldFormatTournamentsSeasonGetResponse(RootModel[List[Tournament]]):
    root: List[Tournament]


class DfsSlateTournament(BaseModel):
    OperatorTournamentID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateID: Optional[int] = None
    SlateTournamentID: Optional[int] = None
    Tournament_1: Optional[Tournament] = Field(None, alias='Tournament')
    TournamentID: Optional[int] = None


class Leaderboard(BaseModel):
    Players: Optional[List[PlayerTournament]] = None
    Tournament_1: Optional[Tournament] = Field(None, alias='Tournament')


class DfsSlate(BaseModel):
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    DfsSlateTournaments: Optional[List[DfsSlateTournament]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfTournaments: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByTournamentTournamentidGetResponse(
    RootModel[List[DfsSlate]]
):
    root: List[DfsSlate]
